name: delete-workflow-runs-action
description: GitHub Action to delete workflow runs
author: Azeem Sajid <azeem.sajid@gmail.com>

branding:
  icon: x
  color: red

runs:
  using: composite
  steps:
    - name: Delete
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/scripts/delete.bash
