name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    # Permissions `actions: write` are required to delete previous workflow runs.
    # Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Delete
      uses: ./
      with:
        keep: 1
