name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    # Permissions required to delete previous workflow runs
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: write
      actions: write

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run
      uses: ./
      with:
        include-disabled-workflows: false
        branch: main
        commit-sha: 1a2b3c4d1a2b3c4d
        creation-date: '2025-02-24T01:00:00Z'
        event: push
        status: completed
        username: iamazeem
        workflow: ci.yml
        exclude-last: 1


