name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Workflow filename to delete previous runs'
        required: false
        default: ci.yml
        type: string
      keep:
        description: 'Number of workflow runs to keep'
        required: false
        default: 1
        type: number

jobs:
  ci:
    runs-on: ubuntu-latest

    # Permissions `actions: write` are required to delete previous workflow runs.
    # Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Delete
      uses: ./
      with:
        workflow: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.workflow || 'ci.yml' }}
        keep: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.keep || 1 }}
